#!/bin/sh

DIALOG_RESULT=$(echo -e 'pavucontrol\nlxrandr\nlxappearance\ngparted' | rofi -dmenu -i -p "Favorite [APP]" -hide-scrollbar -tokenize -lines 9 -eh 1 -width 25 -location 0 -xoffset 0 -yoffset 0 -padding 20 -disable-history -font "ClearSansMedium 13")

echo "This result is : $DIALOG_RESULT"
sleep 1;

if [ "$DIALOG_RESULT" = "pavucontrol" ];
then
    exec pavucontrol

elif [ "$DIALOG_RESULT" = "lxrandr" ];
then
    exec lxrandr

elif [ "$DIALOG_RESULT" = "lxappearance" ];
then
    exec lxappearance

elif [ "$DIALOG_RESULT" = "gparted" ];
then
    exec gparted
fi